// kea-dhcp4.conf — plantilla del servidor DHCP (Kea)
// Los __TOKENS__ los reemplaza entrypoint.sh con las variables del .env
{
    "Dhcp4": {
        "interfaces-config": {
            "interfaces": ["*"]
        },
        "lease-database": {
            "type": "memfile",
            "lfc-interval": 3600
        },
        "subnet4": [
            {
                "subnet": "__DHCP_SUBNET__",
                "pools": [
                    { "pool": "__DHCP_POOL__" }
                ],
                "option-data": [
                    { "name": "domain-name-servers", "data": "__DHCP_DNS__" },
                    { "name": "domain-name", "data": "__DNS_DOMAIN__" },
                    { "name": "routers", "data": "__DHCP_GATEWAY__" },
                    { "name": "ntp-servers", "data": "__DHCP_NTP__" }
                ]
            }
        ],
        "loggers": [
            {
                "name": "kea-dhcp4",
                "output_options": [
                    { "output": "stdout" }
                ],
                "severity": "INFO"
            }
        ]
    }
}