# /etc/dovecot/conf.d/10-master.conf — Listeners de servicios Dovecot

# Auth service: sockets de autenticación
service auth {
  # Socket para que Postfix verifique credenciales (SASL)
  # Postfix se conecta aquí via smtpd_sasl_path = private/auth
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

# Login service: sockets para IMAP/POP3
service login {
}