# /etc/krb5.conf — Kerberos realm SUDOERS.LAN
# provision.sh lo genera automáticamente; acá queda el modelo.

[libdefaults]
    default_realm = SUDOERS.LAN
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true